# Generated by Django 4.2.20 on 2025-03-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_medicalrecord_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='bill',
            field=models.BooleanField(default=False),
        ),
    ]
